### PR TITLE
Implement garbage collector

### LINKED ISSUE #1: No garbage collector
Adding in a garbage collector would make this closer to being a "true" LISP

### PR DESCRIPTION
**Pull request by simmsb**
I've added a simple mark and sweep gc. From my testing it appears to work correctly.
I've ran my source through clang-format, although it appears to have used some global settings and sorted the imports.

Should resolve: #1

### CODE REVIEW

**Comment by Nevexo** [comment]
i did a good one

**Comment by lazear** [comment]
I'll take a look at it this afternoon/tomorrow! Don't worry about the clang-format stuff

**Comment by lazear** [comment]
Overall performance seems good at a first glance. I'll continue doing some testing.

One thing I've noticed is that objects are being free in gc_eval before they are returned and printed. This is unsafe! - but can be fixed by marking ("rooting" it) temporarily.
```c
struct object *gc_eval(struct object *exp, struct object *env) {
    struct object *ret = eval(exp, env);
    // Temporarily mark the object we are returning. It will get swept after a couple cycles
    mark_object(ret);
    run_gc();
    return ret;
}
```

**Comment by simmsb** [comment]
Yep, annoying I didn't spot that earlier. I'll add in a flag that enforce a gc pass every run rather than when the current allocation count goes above gc threshold.

**Comment by lazear** [comment]
````c
/* NOTE: might want to move this to occur every eval call.
 Currently only runs the GC at the end of evalutating a file, or after a repl
prompt.*/
````
I'm glad you caught this - it was my next comment. 
During testing I noticed that evaluating `src/fib.scm` was using as much memory as the original non-GC version. GC needs to run either every eval loop, or during new object allocation. 
There are some pitfalls here though - you will need to make sure that objects currently being evaluated or used during `eval()` are not prematurely collected.

**Comment by lazear** [comment]
I think doing a GC pass during allocation will be the easiest way. Not sure though

**Comment by simmsb** [comment]
Looks like most of the problems were objects being deallocated while they're inside eval. possibly before they're put through define_variable/  set_variable.

**Comment by lazear** [comment]
I'm seeing about a 5x performance hit on an i3-6100 processor on src/fib. Do you think there's a way to mitigate some of the performance impact?

Obviously part of this is due to the design of the interpreter and lack of bytecode/compilation, but a 5x slowdown is quite a lot. The fib bench is also not optimized - on purpose.

**Comment by simmsb** [comment]
I'm going to look into implementing a object pool instead of just mallocing and freeing every time. I'll also start doing some profiling and see what that tells me.

**Comment by lazear** [comment]
Is this ready for a final review? If not, just ping me when it is - I've been pretty busy recently

**Comment by simmsb** [comment]
Yup, It's in a state I'm happy with.
@lazear

**Comment by lazear** [comment]
Looks good to me. How would you like to be attributed?

**Comment by simmsb** [comment]
A link to my gh in a comment somewhere near the GC code is alright for me.

**Pull request merged**
